#!/usr/bin/env bash
# Removes assets that no page references, from git history going forward and
# from disk. Generated by auditing every import in src/. Reclaims ~25 MB.
set -euo pipefail
cd "$(dirname "$0")/.."

git rm -q --ignore-unmatch -- 'public/site/brand/rebel-logo-charcoal.png'
git rm -q --ignore-unmatch -- 'public/site/photos/20210226_181535 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/DSC04015 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/DSC04015.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0000.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0001.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0003.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0004.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0007.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0008.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0010.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0015.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0016.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0017.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0019.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0025.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0028.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0029.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG-20200313-WA0031.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3416 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3417 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3417.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3418 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3418.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3419 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3419.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3425 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3425.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3426 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3426.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3427 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3427 2 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3427 2.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3428 - Copy.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3428.jpg'
git rm -q --ignore-unmatch -- 'public/site/photos/IMG_3434.jpg'
git rm -q --ignore-unmatch -- 'public/site/reels/lighting-01.jpg'
git rm -q --ignore-unmatch -- 'public/site/reels/lighting-01.mp4'
git rm -q --ignore-unmatch -- 'public/site/reels/lighting-02.jpg'
git rm -q --ignore-unmatch -- 'public/site/reels/lighting-02.mp4'
git rm -q --ignore-unmatch -- 'public/site/reels/styling-01.jpg'
git rm -q --ignore-unmatch -- 'public/site/reels/styling-01.mp4'
git rm -q --ignore-unmatch -- 'public/site/reels/styling-02.jpg'
git rm -q --ignore-unmatch -- 'public/site/reels/styling-02.mp4'
git rm -q --ignore-unmatch -- 'public/site/reels/styling-03.jpg'
git rm -q --ignore-unmatch -- 'public/site/reels/styling-03.mp4'

# Orphaned V4 marketing sections. Not imported by anything (so tree-shaken out
# of the bundle already) and they still contain stale Sydney copy, which would
# be wrong if anyone ever wired them back up.
git rm -q --ignore-unmatch -- 'src/components/public/marketing/components.tsx'
git rm -q --ignore-unmatch -- 'src/components/public/marketing/sections/Services.tsx'
git rm -q --ignore-unmatch -- 'src/components/public/marketing/sections/Process.tsx'
git rm -q --ignore-unmatch -- 'src/components/public/marketing/sections/Coverage.tsx'
git rm -q --ignore-unmatch -- 'src/components/public/marketing/sections/Footer.tsx'

# Superseded local encodes and working files (already gitignored, removed from disk)
rm -f public/site/hero.mp4 public/site/hero-scrub.mp4 public/site/hero-still-alt.jpg
rm -f public/site/_pidx_*.jpg public/site/_photoidx_*.jpg public/site/clients/_check.jpg
rm -rf public/site/instagram public/site/photos/_nonphoto

echo "Removed 46 unreferenced files."
echo "Now run: npx tsc --noEmit && npx vite build"
